# Streamlit Configuration - Minimal Working Version
# Only includes valid options for current Streamlit versions

[server]
maxUploadSize = 200

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"